package models

const SystemSettingsPath = "system/settings/"

type SystemSettings struct {
	AllowLinkdownPath              *string                                  `json:"allow-linkdown-path,omitempty"`
	AllowSubnetOverlap             *string                                  `json:"allow-subnet-overlap,omitempty"`
	ApplicationBandwidthTracking   *string                                  `json:"application-bandwidth-tracking,omitempty"`
	Asymroute                      *string                                  `json:"asymroute,omitempty"`
	AsymrouteIcmp                  *string                                  `json:"asymroute-icmp,omitempty"`
	Asymroute6                     *string                                  `json:"asymroute6,omitempty"`
	Asymroute6Icmp                 *string                                  `json:"asymroute6-icmp,omitempty"`
	AuxiliarySession               *string                                  `json:"auxiliary-session,omitempty"`
	Bfd                            *string                                  `json:"bfd,omitempty"`
	BfdDesiredMinTx                *int64                                   `json:"bfd-desired-min-tx,omitempty"`
	BfdDetectMult                  *int64                                   `json:"bfd-detect-mult,omitempty"`
	BfdDontEnforceSrcPort          *string                                  `json:"bfd-dont-enforce-src-port,omitempty"`
	BfdRequiredMinRx               *int64                                   `json:"bfd-required-min-rx,omitempty"`
	BlockLandAttack                *string                                  `json:"block-land-attack,omitempty"`
	CentralNat                     *string                                  `json:"central-nat,omitempty"`
	Comments                       *string                                  `json:"comments,omitempty"`
	ConsolidatedFirewallMode       *string                                  `json:"consolidated-firewall-mode,omitempty"`
	DefaultVoipAlgMode             *string                                  `json:"default-voip-alg-mode,omitempty"`
	DenyTcpWithIcmp                *string                                  `json:"deny-tcp-with-icmp,omitempty"`
	Device                         *string                                  `json:"device,omitempty"`
	DhcpProxy                      *string                                  `json:"dhcp-proxy,omitempty"`
	DhcpProxyInterface             *string                                  `json:"dhcp-proxy-interface,omitempty"`
	DhcpProxyInterfaceSelectMethod *string                                  `json:"dhcp-proxy-interface-select-method,omitempty"`
	DhcpServerIp                   *string                                  `json:"dhcp-server-ip,omitempty"`
	Dhcp6ServerIp                  *string                                  `json:"dhcp6-server-ip,omitempty"`
	DiscoveredDeviceTimeout        *int64                                   `json:"discovered-device-timeout,omitempty"`
	EcmpMaxPaths                   *int64                                   `json:"ecmp-max-paths,omitempty"`
	EmailPortalCheckDns            *string                                  `json:"email-portal-check-dns,omitempty"`
	FirewallSessionDirty           *string                                  `json:"firewall-session-dirty,omitempty"`
	FwSessionHairpin               *string                                  `json:"fw-session-hairpin,omitempty"`
	Gateway                        *string                                  `json:"gateway,omitempty"`
	Gateway6                       *string                                  `json:"gateway6,omitempty"`
	GuiAdvancedPolicy              *string                                  `json:"gui-advanced-policy,omitempty"`
	GuiAllowUnnamedPolicy          *string                                  `json:"gui-allow-unnamed-policy,omitempty"`
	GuiAntivirus                   *string                                  `json:"gui-antivirus,omitempty"`
	GuiApProfile                   *string                                  `json:"gui-ap-profile,omitempty"`
	GuiApplicationControl          *string                                  `json:"gui-application-control,omitempty"`
	GuiDefaultPolicyColumns        *[]SystemSettingsGuiDefaultPolicyColumns `json:"gui-default-policy-columns,omitempty"`
	GuiDhcpAdvanced                *string                                  `json:"gui-dhcp-advanced,omitempty"`
	GuiDnsDatabase                 *string                                  `json:"gui-dns-database,omitempty"`
	GuiDnsfilter                   *string                                  `json:"gui-dnsfilter,omitempty"`
	GuiDomainIpReputation          *string                                  `json:"gui-domain-ip-reputation,omitempty"`
	GuiDosPolicy                   *string                                  `json:"gui-dos-policy,omitempty"`
	GuiDynamicProfileDisplay       *string                                  `json:"gui-dynamic-profile-display,omitempty"`
	GuiDynamicRouting              *string                                  `json:"gui-dynamic-routing,omitempty"`
	GuiEmailCollection             *string                                  `json:"gui-email-collection,omitempty"`
	GuiEndpointControl             *string                                  `json:"gui-endpoint-control,omitempty"`
	GuiEndpointControlAdvanced     *string                                  `json:"gui-endpoint-control-advanced,omitempty"`
	GuiExplicitProxy               *string                                  `json:"gui-explicit-proxy,omitempty"`
	GuiFileFilter                  *string                                  `json:"gui-file-filter,omitempty"`
	GuiFortiapSplitTunneling       *string                                  `json:"gui-fortiap-split-tunneling,omitempty"`
	GuiFortiextenderController     *string                                  `json:"gui-fortiextender-controller,omitempty"`
	GuiIcap                        *string                                  `json:"gui-icap,omitempty"`
	GuiImplicitPolicy              *string                                  `json:"gui-implicit-policy,omitempty"`
	GuiIps                         *string                                  `json:"gui-ips,omitempty"`
	GuiLoadBalance                 *string                                  `json:"gui-load-balance,omitempty"`
	GuiLocalInPolicy               *string                                  `json:"gui-local-in-policy,omitempty"`
	GuiLocalReports                *string                                  `json:"gui-local-reports,omitempty"`
	GuiMulticastPolicy             *string                                  `json:"gui-multicast-policy,omitempty"`
	GuiMultipleInterfacePolicy     *string                                  `json:"gui-multiple-interface-policy,omitempty"`
	GuiMultipleUtmProfiles         *string                                  `json:"gui-multiple-utm-profiles,omitempty"`
	GuiNat4664                     *string                                  `json:"gui-nat46-64,omitempty"`
	GuiObjectColors                *string                                  `json:"gui-object-colors,omitempty"`
	GuiPerPolicyDisclaimer         *string                                  `json:"gui-per-policy-disclaimer,omitempty"`
	GuiPolicyBasedIpsec            *string                                  `json:"gui-policy-based-ipsec,omitempty"`
	GuiPolicyDisclaimer            *string                                  `json:"gui-policy-disclaimer,omitempty"`
	GuiReplacementMessageGroups    *string                                  `json:"gui-replacement-message-groups,omitempty"`
	GuiSecurityProfileGroup        *string                                  `json:"gui-security-profile-group,omitempty"`
	GuiSpamfilter                  *string                                  `json:"gui-spamfilter,omitempty"`
	GuiSslvpnPersonalBookmarks     *string                                  `json:"gui-sslvpn-personal-bookmarks,omitempty"`
	GuiSslvpnRealms                *string                                  `json:"gui-sslvpn-realms,omitempty"`
	GuiSwitchController            *string                                  `json:"gui-switch-controller,omitempty"`
	GuiThreatWeight                *string                                  `json:"gui-threat-weight,omitempty"`
	GuiTrafficShaping              *string                                  `json:"gui-traffic-shaping,omitempty"`
	GuiVideofilter                 *string                                  `json:"gui-videofilter,omitempty"`
	GuiVoipProfile                 *string                                  `json:"gui-voip-profile,omitempty"`
	GuiVpn                         *string                                  `json:"gui-vpn,omitempty"`
	GuiWafProfile                  *string                                  `json:"gui-waf-profile,omitempty"`
	GuiWanLoadBalancing            *string                                  `json:"gui-wan-load-balancing,omitempty"`
	GuiWanoptCache                 *string                                  `json:"gui-wanopt-cache,omitempty"`
	GuiWebfilter                   *string                                  `json:"gui-webfilter,omitempty"`
	GuiWebfilterAdvanced           *string                                  `json:"gui-webfilter-advanced,omitempty"`
	GuiWirelessController          *string                                  `json:"gui-wireless-controller,omitempty"`
	GuiZtna                        *string                                  `json:"gui-ztna,omitempty"`
	H323DirectModel                *string                                  `json:"h323-direct-model,omitempty"`
	HttpExternalDest               *string                                  `json:"http-external-dest,omitempty"`
	IkeDnFormat                    *string                                  `json:"ike-dn-format,omitempty"`
	IkePolicyRoute                 *string                                  `json:"ike-policy-route,omitempty"`
	IkePort                        *int64                                   `json:"ike-port,omitempty"`
	IkeQuickCrashDetect            *string                                  `json:"ike-quick-crash-detect,omitempty"`
	IkeSessionResume               *string                                  `json:"ike-session-resume,omitempty"`
	ImplicitAllowDns               *string                                  `json:"implicit-allow-dns,omitempty"`
	Ip                             *[]string                                `json:"ip,omitempty"`
	Ip6                            *string                                  `json:"ip6,omitempty"`
	LinkDownAccess                 *string                                  `json:"link-down-access,omitempty"`
	LldpReception                  *string                                  `json:"lldp-reception,omitempty"`
	LldpTransmission               *string                                  `json:"lldp-transmission,omitempty"`
	LocationId                     *string                                  `json:"location-id,omitempty"`
	MacTtl                         *int64                                   `json:"mac-ttl,omitempty"`
	Manageip                       *string                                  `json:"manageip,omitempty"`
	Manageip6                      *string                                  `json:"manageip6,omitempty"`
	MulticastForward               *string                                  `json:"multicast-forward,omitempty"`
	MulticastSkipPolicy            *string                                  `json:"multicast-skip-policy,omitempty"`
	MulticastTtlNotchange          *string                                  `json:"multicast-ttl-notchange,omitempty"`
	NgfwMode                       *string                                  `json:"ngfw-mode,omitempty"`
	Opmode                         *string                                  `json:"opmode,omitempty"`
	PrpTrailerAction               *string                                  `json:"prp-trailer-action,omitempty"`
	SccpPort                       *int64                                   `json:"sccp-port,omitempty"`
	SctpSessionWithoutInit         *string                                  `json:"sctp-session-without-init,omitempty"`
	SesDeniedTraffic               *string                                  `json:"ses-denied-traffic,omitempty"`
	SipExpectation                 *string                                  `json:"sip-expectation,omitempty"`
	SipNatTrace                    *string                                  `json:"sip-nat-trace,omitempty"`
	SipSslPort                     *int64                                   `json:"sip-ssl-port,omitempty"`
	SipTcpPort                     *int64                                   `json:"sip-tcp-port,omitempty"`
	SipUdpPort                     *int64                                   `json:"sip-udp-port,omitempty"`
	SnatHairpinTraffic             *string                                  `json:"snat-hairpin-traffic,omitempty"`
	Status                         *string                                  `json:"status,omitempty"`
	StrictSrcCheck                 *string                                  `json:"strict-src-check,omitempty"`
	TcpSessionWithoutSyn           *string                                  `json:"tcp-session-without-syn,omitempty"`
	Utf8SpamTagging                *string                                  `json:"utf8-spam-tagging,omitempty"`
	V4EcmpMode                     *string                                  `json:"v4-ecmp-mode,omitempty"`
	VpnStatsLog                    *string                                  `json:"vpn-stats-log,omitempty"`
	VpnStatsPeriod                 *int64                                   `json:"vpn-stats-period,omitempty"`
	WccpCacheEngine                *string                                  `json:"wccp-cache-engine,omitempty"`
}

type SystemSettingsGuiDefaultPolicyColumns struct {
	Name *string `json:"name,omitempty"`
}
